# frozen_string_literal: true

require "fileutils"
require "open3"
require "minitest/autorun"

class ExamplesSuiteTest < Minitest::Test
  PROJECT_ROOT = File.expand_path("..", __dir__)
  BUILD_RTL_DIR = File.join(PROJECT_ROOT, "build", "rtl")

  EXAMPLES = {
    "counter.rb" => {
      outputs: ["counter.sv"],
      lint_files: ["build/rtl/counter.sv"]
    },
    "top.rb" => {
      outputs: ["top.sv"],
      lint_files: ["build/rtl/counter.sv", "build/rtl/top.sv"]
    },
    "syntax_showcase.rb" => {
      outputs: ["syntax_showcase.sv"],
      lint_files: ["build/rtl/syntax_showcase.sv"]
    },
    "storage_streams.rb" => {
      outputs: ["storage_streams.sv"],
      lint_files: ["build/rtl/storage_streams.sv"]
    },
    "mux_cases.rb" => {
      outputs: ["mux_cases.sv"],
      lint_files: ["build/rtl/mux_cases.sv"]
    },
    "import_demo.rb" => {
      outputs: ["import_demo.sv"],
      lint_files: ["examples/imported_counter.sv", "build/rtl/import_demo.sv"]
    }
  }.freeze

  def test_examples_generate_sv_and_pass_verilator
    FileUtils.mkdir_p(BUILD_RTL_DIR)
    EXAMPLES.each_value do |spec|
      spec[:outputs].each { |output| FileUtils.rm_f(File.join(BUILD_RTL_DIR, output)) }
    end

    EXAMPLES.each do |script, spec|
      stdout, stderr, status = Open3.capture3("ruby", File.join("examples", script), chdir: PROJECT_ROOT)
      assert status.success?, <<~MSG
        expected `ruby examples/#{script}` to succeed
        stdout:
        #{stdout}
        stderr:
        #{stderr}
      MSG

      spec[:outputs].each do |output|
        assert File.exist?(File.join(BUILD_RTL_DIR, output)), "expected #{output} to be generated by #{script}"
      end
    end

    syntax_showcase_sv = File.read(File.join(BUILD_RTL_DIR, "syntax_showcase.sv"))
    shared_domain_blocks = syntax_showcase_sv.scan("always_ff @(negedge clk or negedge rst_n)").length
    assert_operator shared_domain_blocks, :>=, 2, "expected syntax_showcase.sv to demonstrate multiple always_ff blocks sharing one with_clk_and_rst domain"

    EXAMPLES.each do |script, spec|
      stdout, stderr, status = Open3.capture3("verilator", "--lint-only", *spec[:lint_files], chdir: PROJECT_ROOT)
      assert status.success?, <<~MSG
        expected generated SV for #{script} to pass `verilator --lint-only`
        stdout:
        #{stdout}
        stderr:
        #{stderr}
      MSG
    end
  end
end
