# frozen_string_literal: true

require "fileutils"
require "open3"
require "minitest/autorun"

class ExamplesSuiteTest < Minitest::Test
  PROJECT_ROOT = File.expand_path("..", __dir__)
  BUILD_RTL_DIR = File.join(PROJECT_ROOT, "build", "rtl")

  EXAMPLES = {
    "counter.rb" => {
      outputs: ["counter.sv"],
      lint_files: ["build/rtl/counter.sv"]
    },
    "auto_dedup.rb" => {
      outputs: ["auto_dedup_counter.sv", "auto_dedup_top.sv"],
      lint_files: ["build/rtl/auto_dedup_counter.sv", "build/rtl/auto_dedup_top.sv"]
    },
    "manual_dedup.rb" => {
      outputs: ["manual_dedup_counter.sv", "manual_dedup_top.sv"],
      lint_files: ["build/rtl/manual_dedup_counter.sv", "build/rtl/manual_dedup_top.sv"]
    },
    "syntax_showcase.rb" => {
      outputs: ["syntax_showcase.sv"],
      lint_files: ["build/rtl/syntax_showcase.sv"]
    },
    "storage_streams.rb" => {
      outputs: ["storage_streams.sv"],
      lint_files: ["build/rtl/storage_streams.sv"]
    },
    "mux_cases.rb" => {
      outputs: ["mux_cases.sv"],
      lint_files: ["build/rtl/mux_cases.sv"]
    },
    "import_demo.rb" => {
      outputs: ["import_demo.sv"],
      lint_files: ["examples/imported_counter.sv", "build/rtl/import_demo.sv"]
    },
    "const_demo.rb" => {
      outputs: ["const_demo.sv"],
      lint_files: ["build/rtl/const_demo.sv"]
    },
    "macro_demo.rb" => {
      outputs: ["macro_demo.sv"],
      lint_files: ["-DSIM", "build/rtl/macro_demo.sv"]
    },
    "generate_demo.rb" => {
      outputs: ["generate_demo.sv", "PipeStage.sv", "sv_pipe_stage.sv"],
      lint_files: ["build/rtl/PipeStage.sv", "build/rtl/sv_pipe_stage.sv", "build/rtl/generate_demo.sv"]
    },
    "curried_params.rb" => {
      outputs: ["curried_top.sv", "curried_param_counter.sv", "curried_param_counter_1.sv"],
      lint_files: ["build/rtl/curried_param_counter.sv", "build/rtl/curried_param_counter_1.sv", "build/rtl/curried_top.sv"]
    },
    "verilog_wrapper.rb" => {
      outputs: ["inner_module.sv", "inner_module_wrapper.sv"],
      lint_files: ["build/rtl/inner_module.sv", "build/rtl/inner_module_wrapper.sv"]
    }
  }.freeze

  def test_examples_generate_sv_and_pass_verilator
    FileUtils.mkdir_p(BUILD_RTL_DIR)
    EXAMPLES.each_value do |spec|
      spec[:outputs].each { |output| FileUtils.rm_f(File.join(BUILD_RTL_DIR, output)) }
    end

    EXAMPLES.each do |script, spec|
      stdout, stderr, status = Open3.capture3("ruby", File.join("examples", script), chdir: PROJECT_ROOT)
      assert status.success?, <<~MSG
        expected `ruby examples/#{script}` to succeed
        stdout:
        #{stdout}
        stderr:
        #{stderr}
      MSG

      spec[:outputs].each do |output|
        assert File.exist?(File.join(BUILD_RTL_DIR, output)), "expected #{output} to be generated by #{script}"
      end
    end

    syntax_showcase_sv = File.read(File.join(BUILD_RTL_DIR, "syntax_showcase.sv"))
    shared_domain_blocks = syntax_showcase_sv.scan("always_ff @(negedge clk or negedge rst_n)").length
    assert_operator shared_domain_blocks, :>=, 2, "expected syntax_showcase.sv to demonstrate multiple always_ff blocks sharing one with_clk_and_rst domain"

    auto_dedup_top_sv = File.read(File.join(BUILD_RTL_DIR, "auto_dedup_top.sv"))
    refute_includes auto_dedup_top_sv, "AutoDedupCounter_1", "expected automatic dedup example to collapse identical Counter templates to one module definition"
    assert_includes auto_dedup_top_sv, "u_stage_a_dout;", "expected automatic dedup example to declare an auto-generated inter-module wire"
    assert_includes auto_dedup_top_sv, ".dout(u_stage_a_dout)"
    assert_includes auto_dedup_top_sv, ".din(u_stage_a_dout)"

    manual_dedup_top_sv = File.read(File.join(BUILD_RTL_DIR, "manual_dedup_top.sv"))
    refute_includes manual_dedup_top_sv, "ManualDedupCounter_1", "expected manual dedup example to collapse identical Counter templates to one module definition"
    assert_includes manual_dedup_top_sv, "u_stage_a_dout;", "expected manual dedup example to declare an auto-generated inter-module wire"
    assert_includes manual_dedup_top_sv, ".dout(u_stage_a_dout)"
    assert_includes manual_dedup_top_sv, ".din(u_stage_a_dout)"

    EXAMPLES.each do |script, spec|
      stdout, stderr, status = Open3.capture3("verilator", "--lint-only", *spec[:lint_files], chdir: PROJECT_ROOT)
      assert status.success?, <<~MSG
        expected generated SV for #{script} to pass `verilator --lint-only`
        stdout:
        #{stdout}
        stderr:
        #{stderr}
      MSG
    end
  end
end
