# frozen_string_literal: true

require "fileutils"
require "open3"
require "minitest/autorun"

class ExamplesSuiteTest < Minitest::Test
  PROJECT_ROOT = File.expand_path("..", __dir__)
  BUILD_RTL_DIR = File.join(PROJECT_ROOT, "build", "rtl")

  EXAMPLES = {
    "counter.rb" => {
      outputs: ["counter.sv"],
      lint_files: ["build/rtl/counter.sv"]
    },
    "syntax_showcase.rb" => {
      outputs: ["syntax_showcase.sv"],
      lint_files: ["build/rtl/syntax_showcase.sv"]
    },
    "storage_streams.rb" => {
      outputs: ["storage_streams.sv"],
      lint_files: ["build/rtl/storage_streams.sv"]
    },
    "mux_cases.rb" => {
      outputs: ["mux_cases.sv"],
      lint_files: ["build/rtl/mux_cases.sv"]
    },
    "import_demo.rb" => {
      outputs: ["import_demo.sv"],
      lint_files: ["examples/imported_counter.sv", "build/rtl/import_demo.sv"]
    },
    "const_demo.rb" => {
      outputs: ["const_demo.sv"],
      lint_files: ["build/rtl/const_demo.sv"]
    },
    "macro_demo.rb" => {
      outputs: ["macro_demo.sv"],
      lint_files: ["-DSIM", "build/rtl/macro_demo.sv"]
    },
    "generate_demo.rb" => {
      outputs: ["generate_demo.sv", "pipe_stage.sv"],
      lint_files: ["build/rtl/pipe_stage.sv", "build/rtl/generate_demo.sv"]
    },
    "global_dedup.rb" => {
      outputs: ["dedup_counter.sv", "dedup_counter_1.sv", "dedup_adder.sv", "dedup_top.sv"],
      lint_files: ["-Wno-MULTITOP", "build/rtl/dedup_counter.sv", "build/rtl/dedup_counter_1.sv", "build/rtl/dedup_adder.sv", "build/rtl/dedup_top.sv"]
    },
    "curried_params.rb" => {
      outputs: ["curried_top.sv", "param_counter.sv", "param_counter_1.sv"],
      lint_files: ["build/rtl/param_counter.sv", "build/rtl/param_counter_1.sv", "build/rtl/curried_top.sv"]
    },
    "verilog_wrapper.rb" => {
      outputs: ["inner_module.sv", "inner_module_wrapper.sv", "bundle_module.sv", "bundle_module_wrapper.sv",
                "mem_bundle_module.sv", "mem_bundle_module_wrapper.sv"],
      lint_files: ["-Wno-MULTITOP",
                   "build/rtl/inner_module.sv", "build/rtl/inner_module_wrapper.sv",
                   "build/rtl/bundle_module.sv", "build/rtl/bundle_module_wrapper.sv",
                   "build/rtl/mem_bundle_module.sv", "build/rtl/mem_bundle_module_wrapper.sv"]
    },
    "sv_plugin_demo.rb" => {
      outputs: ["sv_plugin_demo.sv"],
      lint_files: ["build/rtl/sv_plugin_demo.sv"]
    },
    "bundle_and_interface.rb" => {
      outputs: ["pixel_processor.sv", "packet_router.sv", "pipe_reg.sv", "pipe_reg_1.sv"],
      lint_files: [
        "-Wno-MULTITOP",
        "build/rtl/pixel_processor.sv",
        "build/rtl/packet_router.sv",
        "build/rtl/pipe_reg.sv",
        "build/rtl/pipe_reg_1.sv"
      ]
    },
    "case_demo.rb" => {
      outputs: ["case_demo.sv"],
      lint_files: ["build/rtl/case_demo.sv"]
    },
    "pop_count_demo.rb" => {
      outputs: ["pop_count_demo.sv"],
      lint_files: ["build/rtl/pop_count_demo.sv"]
    },
    "type_conv_demo.rb" => {
      outputs: ["type_conv_demo.sv"],
      lint_files: ["build/rtl/type_conv_demo.sv"]
    }
  }.freeze

  def test_examples_generate_sv_and_pass_verilator
    FileUtils.mkdir_p(BUILD_RTL_DIR)
    EXAMPLES.each_value do |spec|
      spec[:outputs].each { |output| FileUtils.rm_f(File.join(BUILD_RTL_DIR, output)) }
    end

    EXAMPLES.each do |script, spec|
      stdout, stderr, status = Open3.capture3("ruby", "-Ilib", File.join("examples", script), "-o", BUILD_RTL_DIR, chdir: PROJECT_ROOT)
      assert status.success?, <<~MSG
        expected `ruby examples/#{script} -o #{BUILD_RTL_DIR}` to succeed
        stdout:
        #{stdout}
        stderr:
        #{stderr}
      MSG

      spec[:outputs].each do |output|
        assert File.exist?(File.join(BUILD_RTL_DIR, output)), "expected #{output} to be generated by #{script}"
      end
    end

    syntax_showcase_sv = File.read(File.join(BUILD_RTL_DIR, "syntax_showcase.sv"))
    shared_domain_blocks = syntax_showcase_sv.scan("always_ff @(negedge clk or negedge rst_n)").length
    assert_operator shared_domain_blocks, :>=, 2, "expected syntax_showcase.sv to demonstrate multiple always_ff blocks sharing one with_clk_and_rst domain"

    dedup_top_sv = File.read(File.join(BUILD_RTL_DIR, "dedup_top.sv"))
    # auto dedup: two width=8 counters share one DedupCounter template
    assert_includes dedup_top_sv, "DedupCounter u_cnt_a", "expected auto dedup to instantiate DedupCounter"
    assert_includes dedup_top_sv, "DedupCounter u_cnt_b", "expected auto dedup to reuse same DedupCounter"
    refute_includes dedup_top_sv, "DedupCounter_2", "expected no extra variants beyond _1"
    # manual dedup: definition(width: 16) + instance → variant _1
    assert_includes dedup_top_sv, "DedupCounter_1 u_cnt_c", "expected manual dedup to create variant DedupCounter_1"
    # auto-wiring: cnt_a.dout → cnt_b.din via parent-local wire
    assert_includes dedup_top_sv, "u_cnt_a_dout;", "expected auto-generated inter-module wire"
    assert_includes dedup_top_sv, ".dout(u_cnt_a_dout)"
    assert_includes dedup_top_sv, ".din(u_cnt_a_dout)"
    # unused port annotation
    assert_includes dedup_top_sv, "/* unused port */", "expected unused port annotation"

    EXAMPLES.each do |script, spec|
      stdout, stderr, status = Open3.capture3("verilator", "--lint-only", *spec[:lint_files], chdir: PROJECT_ROOT)
      assert status.success?, <<~MSG
        expected generated SV for #{script} to pass `verilator --lint-only`
        stdout:
        #{stdout}
        stderr:
        #{stderr}
      MSG
    end
  end
end
