# frozen_string_literal: true

require "minitest/autorun"
require "fileutils"
require "open3"

class XmakeRtlTest < Minitest::Test
  PROJECT_ROOT = File.expand_path("..", __dir__)
  BUILD_DIR = File.join(PROJECT_ROOT, "build")
  COUNTER_SV = File.join(PROJECT_ROOT, "build", "rtl", "counter.sv")
  DEDUP_TOP_SV = File.join(PROJECT_ROOT, "build", "rtl", "dedup_top.sv")

  def test_xmake_rtl_runs_example_script_from_examples_by_default
    FileUtils.rm_f(COUNTER_SV)

    stdout, stderr, status = Open3.capture3("xmake", "rtl", "-f", "counter", chdir: PROJECT_ROOT)

    assert status.success?, "expected `xmake rtl -f counter` to succeed\nstdout:\n#{stdout}\nstderr:\n#{stderr}"
    assert File.exist?(COUNTER_SV), "expected #{COUNTER_SV} to be generated"
    assert_operator File.size(COUNTER_SV), :>, 0
  end

  def test_xmake_rtl_accepts_a_custom_directory
    stdout, stderr, status = Open3.capture3("xmake", "rtl", "-f", "custom_demo", "-d", "test/fixtures/rtltask", chdir: PROJECT_ROOT)

    assert status.success?, "expected `xmake rtl -f custom_demo -d test/fixtures/rtltask` to succeed\nstdout:\n#{stdout}\nstderr:\n#{stderr}"
    assert_includes stdout, "rtl fixture ok"
  end

  def test_xmake_rtl_runs_global_dedup_example
    FileUtils.rm_f(DEDUP_TOP_SV)

    stdout, stderr, status = Open3.capture3("xmake", "rtl", "-f", "global_dedup", chdir: PROJECT_ROOT)

    assert status.success?, "expected `xmake rtl -f global_dedup` to succeed\nstdout:\n#{stdout}\nstderr:\n#{stderr}"
    assert File.exist?(DEDUP_TOP_SV), "expected #{DEDUP_TOP_SV} to be generated"
  end

  def test_xmake_rtl_lists_available_examples_with_alias_and_feature_summary
    stdout, stderr, status = Open3.capture3("xmake", "rtl", "-l", chdir: PROJECT_ROOT)

    assert status.success?, "expected `xmake rtl -l` to succeed\nstdout:\n#{stdout}\nstderr:\n#{stderr}"
    assert_includes stdout, "alias"
    assert_includes stdout, "counter"
    assert_includes stdout, "ctr"
    assert_includes stdout, "parameterized sequential counter"
    assert_includes stdout, "sv_plugin_demo"
    assert_includes stdout, "svp"
    assert_includes stdout, "inline SystemVerilog"
  end

  def test_xmake_rtl_accepts_example_aliases
    FileUtils.rm_f(COUNTER_SV)

    stdout, stderr, status = Open3.capture3("xmake", "rtl", "-f", "ctr", chdir: PROJECT_ROOT)

    assert status.success?, "expected `xmake rtl -f ctr` to succeed\nstdout:\n#{stdout}\nstderr:\n#{stderr}"
    assert File.exist?(COUNTER_SV), "expected #{COUNTER_SV} to be generated by alias"
  end

  def test_xmake_clean_removes_build_directory
    stale_file = File.join(BUILD_DIR, "stale.txt")
    FileUtils.mkdir_p(BUILD_DIR)
    File.write(stale_file, "stale build output")

    stdout, stderr, status = Open3.capture3("xmake", "clean", chdir: PROJECT_ROOT)

    assert status.success?, "expected `xmake clean` to succeed\nstdout:\n#{stdout}\nstderr:\n#{stderr}"
    refute Dir.exist?(BUILD_DIR), "expected #{BUILD_DIR} to be removed by `xmake clean`"
  end
end
